import { PROFILES_TYPES, TRANSOM_TEMPLATES, LEAF_LIMITS, MATERIALS_ON_SIDE_RULES, PROFILES_PADDINGS, PROFILES_AVAILABLE_DECOR_PRESETS} from './modules/configs.js' //ToDo configs for different modules
import {DECOR_PRESETS} from "./modules/decorPresets.js"
import { PRICES } from './modules/prices.js'

export { PROFILES_TYPES, TRANSOM_TEMPLATES, LEAF_LIMITS, PRICES, MATERIALS_ON_SIDE_RULES, PROFILES_PADDINGS, DECOR_PRESETS, PROFILES_AVAILABLE_DECOR_PRESETS}