

export const PRICES = {
    "s4139_G": {
        "id": "s4139_G",
        "name": "Профиль S 41х39",
        "param1": "6",
        "param2": "1.2",
        "param3": "6",
        "param4": "120",
        "weight": 1.242,
        "unit": "мп",
        "priceIn": 8.9,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "p0159_G": {
        "id": "p0159_G",
        "name": "Профиль АВД 0159",
        "param1": "23",
        "param2": "1.2",
        "param3": "5.5",
        "param4": "65",
        "weight": 1.303,
        "unit": "мп",
        "priceIn": 7.16,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

    "s532_G": {
        "id": "s532_G",
        "name": "Профиль S 5х32",
        "param1": "",
        "param2": "1.2",
        "param3": "6",
        "param4": "40",
        "weight": 0.219,
        "unit": "мп",
        "priceIn": 1.76,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

    "p7967_G": {
        "id": "p7967_G",
        "name": "Профиль АВД 7967",
        "param1": "23",
        "param2": "1.2",
        "param3": "5.5",
        "param4": "65",
        "weight": 1.303,
        "unit": "мп",
        "priceIn": 7.16,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

    "dowel_chapai": { //ToDo нет в базе
        "id": "dowel_chapai",
        "name": "Дюбель чапай",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "prF1_G": {
        "id": "prF1_G",
        "name": "Сухарь",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0.37,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "fix440_G": {
        "id": "fix440_G",
        "name": "Саморез 4х40",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0.02,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "fix7985_G": {
        "id": "fix7985_G",
        "name": "Винт M4х14 DIN 7985",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "fix520_G": {
        "id": "fix520_G",
        "name": "Винт М5 х 20",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0.012,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "screwM20": {
        "id": "screwM20",
        "type": "",
        "group": "",
        "name": "Винт М4х20/25 под замок",
        "image": "",
        "param1": "",
        "param2": "",
        "param3": "",
        "unit": "шт",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "seltht4_G": {
        "id": "seltht4_G",
        "name": "Уплотнитель ш1/т1 4мм",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "мп",
        "priceIn": 0.22,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "sealAl43_G": {
        "id": "sealAl43_G",
        "name": "Уплотнитель АЛ-43",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "мп",
        "priceIn": 0.37,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "rigelDefault": {
        "id": "rigelDefault",
        "name": "Ригель обычный",
        "unit": "шт",
        "priceIn": 5,
        "priceEUR": 21.45,
        "priceUSD": 23.6,
        "priceRUB": 2027.03,
        "priceBYN": 72.93,
        "pricePLN": 92.23,
        "price": 0
    },
    "film17500del_D": {
        "id": "film17500del_D",
        "name": "Пленка стрейч 17*500*384",
        "param1": "",
        "param2": "",
        "param3": "",
        "param4": "",
        "weight": 0,
        "unit": "кг",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "paper500_G": {
        "id": "paper500_G",
        "name": "Гофрокартон 500х2150",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0.419,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "lidModula": {
        "id": "lidModula",
        "name": "Крышка Modula",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 13.83,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },
    "fix430_G": { //ToDo нет в базе
        "id": "fix430_G",
        "name": "Винт М4 х 30",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

    "corner-100-100-8": { //ToDo нет в базе
        "id": "corner-100-100-8",
        "name": "Уголок 100х100х8 ",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn":0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

    "plate-27-200-4": { //ToDo нет в базе
        "id": "plate-27-200-4",
        "name": "Пластина 27х200х4",
        "param1": "",
        "param2": "",
        "weight": 0,
        "unit": "шт",
        "priceIn": 0,
        "priceEUR": 0,
        "priceUSD": 0,
        "priceRUB": 0,
        "priceBYN": 0,
        "pricePLN": 0,
        "price": 0
    },

}